# Generated by Django 3.0 on 2020-11-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredents', models.CharField(max_length=200)),
                ('processmaking', models.CharField(max_length=200)),
            ],
        ),
    ]
